In [1]:
# Ho caricato il file csv ed ho inserito il na_values che mi trasforma il '?' in valore nullo

import pandas as pd
import numpy as np

df = pd.read_csv('C:/Users/infob/Desktop/python/nuovo.py/Pandas/Esercizi develhope/World_Alcohol_Dataset - MAIN (1).csv', na_values='?')

# Sostituisco i valori nulli con la mediana, poichè la std è abbastanza alta e quindi 
# ho dispersione dei valori

df.fillna(round(df['beer_servings'].median(),2), inplace=True)
df.fillna(round(df['spirit_servings'].median(),2), inplace=True)
df.fillna(round(df['wine_servings'].median(),2), inplace=True)

Write a Pandas program to extract specific records from the world alcohol consumption dataset, starting from the 2nd row, and selecting every 5th row thereafter.

In [2]:
# in quetso modo io vado a dirgli di prendere dalla riga 2 sino alla fine ma con lo step di 5,
# cioè visualizza dalla 2 alla fine del dataset, prendendo ogni 5 righe

df[2::5]

,country,beer_servings,spirit_servings,wine_servings,life_expentancy,region,gdp_per_capita
2,Algeria,25.0,0.0,14.0,75.6,NORTHERN AFRICA,6000
7,Australia,261.0,72.0,212.0,82.8,OCEANIA,29000
12,Bangladesh,0.0,0.0,0.0,71.8,ASIA (EX. NEAR EAST),1900
17,Benin,34.0,4.0,13.0,60.0,SUB-SAHARAN AFRICA,1100
22,Brazil,245.0,145.0,16.0,75.0,LATIN AMER. & CARIB,7600
27,Cape Verde,144.0,56.0,16.0,73.3,SUB-SAHARAN AFRICA,1400
32,Chad,15.0,1.0,1.0,53.1,SUB-SAHARAN AFRICA,1200
37,Congo,76.0,1.0,9.0,64.7,SUB-SAHARAN AFRICA,700
42,Cyprus,192.0,154.0,113.0,85.0,NEAR EAST,19200
47,Democratic Republic of the Congo,32.0,3.0,1.0,59.8,SUB-SAHARAN AFRICA,700
52,Eritrea,18.0,0.0,0.0,64.7,SUB-SAHARAN AFRICA,700
57,France,127.0,151.0,370.0,82.4,WESTERN EUROPE,27600
62,Ghana,31.0,3.0,10.0,62.4,SUB-SAHARAN AFRICA,2200
67,Guinea-Bissau,28.0,31.0,21.0,58.9,SUB-SAHARAN AFRICA,800
72,Iceland,233.0,61.0,78.0,82.7,WESTERN EUROPE,30900
77,Ireland,313.0,118.0,165.0,81.4,WESTERN EUROPE,29600
82,Jordan,6.0,21.0,1.0,74.1,NEAR EAST,4300
87,Kyrgyzstan,31.0,97.0,6.0,71.1,C.W. OF IND. STATES,1600
92,Liberia,19.0,152.0,2.0,61.4,SUB-SAHARAN AFRICA,1000
97,Madagascar,26.0,15.0,4.0,65.5,SUB-SAHARAN AFRICA,800
102,Malta,149.0,100.0,120.0,81.7,WESTERN EUROPE,17700
107,Mongolia,77.0,189.0,8.0,68.8,ASIA (EX. NEAR EAST),1800
112,Nepal,5.0,6.0,0.0,69.2,ASIA (EX. NEAR EAST),1400
117,Nigeria,42.0,5.0,2.0,54.5,SUB-SAHARAN AFRICA,900
122,Panama,285.0,104.0,18.0,77.8,LATIN AMER. & CARIB,6300
127,Poland,343.0,215.0,56.0,77.5,EASTERN EUROPE,11100
132,Rwanda,43.0,2.0,0.0,66.1,SUB-SAHARAN AFRICA,1300
137,Seychelles,157.0,25.0,51.0,73.2,SUB-SAHARAN AFRICA,7800
142,Solomon Islands,56.0,11.0,1.0,69.2,OCEANIA,1700
147,Sri Lanka,16.0,104.0,0.0,74.9,ASIA (EX. NEAR EAST),3700
152,Switzerland,185.0,100.0,280.0,83.4,WESTERN EUROPE,32700
157,East Timor,1.0,1.0,4.0,68.3,ASIA (EX. NEAR EAST),500
162,Turkey,51.0,22.0,7.0,75.8,NEAR EAST,6700
167,United Kingdom,219.0,126.0,195.0,81.2,WESTERN EUROPE,27700
172,Venezuela,333.0,100.0,3.0,74.1,LATIN AMER. & CARIB,4800